# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NativeSocket' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SocketRocket', '~> 0.5.1'
  # Pods for NativeSocket

end
